### ISSUE TITLE
Embedding generation failed

### ISSUE THREAD

**Issue by BTPTest2021** [SAP-samples/cap-llm-plugin-samples#11]
After uploading the file and attempting to Generate Embeddings, the error “Embeddings generation failed, please try again” occurs.
I don't have SuccessFactors and have adjusted the code a bit to work without it, is there any way to resolve this?

The log of the bas terminal is as follows.

[cds] - server listening on { url: 'http://localhost:4004' }
[cds] - launched at 8/27/2024, 5:51:05 AM, version: 7.7.0, in: 555.999ms
[cds] - [ terminate with ^C ]

[odata] - GET /odata/v4/chat/$metadata?sap-language=EN 
[odata] - HEAD /odata/v4/chat/ 
[odata] - GET /odata/v4/embedding-storage/$metadata?sap-language=EN 
[odata] - HEAD /odata/v4/embedding-storage/ 
[odata] - POST /odata/v4/chat/$batch 
[odata] - > READ Conversation {
  '$orderby': 'last_update_time desc',
  '$select': 'cID,creation_time,title,userID',
  '$skip': '0',
  '$top': '15'
}
[pool] - effective pool configuration: {
  min: 0,
  max: 100,
  testOnBorrow: true,
  fifo: false,
  acquireTimeoutMillis: 10000,
  softIdleTimeoutMillis: 30000,
  idleTimeoutMillis: 30000,
  evictionRunIntervalMillis: 60000,
  numTestsPerEvictionRun: 34
}
[odata] - POST /odata/v4/embedding-storage/$batch 
[odata] - > READ Files {
  '$orderby': 'createdAt desc',
  '$select': 'ID,fileName,mediaType,size',
  '$skip': '0',
  '$top': '5'
}
[odata] - POST /odata/v4/embedding-storage/storeEmbeddings 
[cds] - connect to cap-llm-plugin > cap-llm-plugin/srv/cap-llm-plugin.js 
Document presence check result for UUID 1ddce6d8-3bff-4a9c-8b66-31d5446b4528: [
  {
    ID: '1ddce6d8-3bff-4a9c-8b66-31d5446b4528',
    createdAt: '2024-08-26T10:45:37.359Z',
    createdBy: 'dummy',
    modifiedAt: '2024-08-26T10:45:37.359Z',
    modifiedBy: 'dummy',
    mediaType: 'application/pdf',
    fileName: 'annual-leave-policy-template.pdf',
    size: '102447'
  }
]
[cds] - stream method is deprecated and will be removed in upcoming releases!
Stream creation failed for UUID: 1ddce6d8-3bff-4a9c-8b66-31d5446b4528
Error while generating and storing vector embeddings: Error: Failed to retrieve document stream from database.
    at ApplicationService.<anonymous> (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/srv/embedding-storage.js:68:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
    at async ApplicationService.handle (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
    at async /home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/action.js:53:16
[cds] - Error: Failed to retrieve document stream from database.
    at ApplicationService.<anonymous> (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/srv/embedding-storage.js:68:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
    at async ApplicationService.handle (/home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
    at async /home/user/projects/cap-llm-plugin-samples/samples/hr-approval-rag-usecase/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/action.js:53:16 {
  id: '1982603',
  level: 'ERROR',
  timestamp: 1724737895605
}

**Comment by feng-lia** [comment]
as your error message indicating : [cds] - stream method is deprecated and will be removed in upcoming releases
you are using a different cds version as the sample.

**Comment by BTPTest2021** [comment]
Could you tell the cds version used in the sample? Where should I update to use the same cds version as the sample?

**Comment by feng-lia** [comment]
> Could you tell the cds version used in the sample? Where should I update to use the same cds version as the sample?

you can go to NPM website to check the versions of @sap/cds,  guess you need an older version like 7.6.3 or something around that; then under project folder:
package.json -> dependencies ->  "@sap/cds": “7.6.3”

**Comment by BTPTest2021** [comment]
The cds version was originally specified as 7.6.3, but the error has not yet been resolved.
