### ISSUE TITLE
cap-llm-plugin vs SAP Cloud SDK for AI

### ISSUE THREAD

**Issue by cocquerel** [SAP-samples/cap-llm-plugin-samples#13]
Could you please clarify the positioning of cap-llm-plugin versus the new  [SAP Cloud SDK for AI](https://github.com/SAP/ai-sdk-js ) ?
The 2 libraries look to me a bit overlapping specially when document grounding will be part of orchestration.

**Comment by jjtang1985** [comment]
> SAP Cloud SDK for AI is the official Software Development Kit (SDK) for SAP AI Core, SAP Generative AI Hub, and Orchestration Service.

I'll pick the summary from the [Readme](https://github.com/SAP/ai-sdk-js/blob/main/README.md) of SAP Cloud SDK for AI.

The SDK will support the grounding module of the orchestration soon, after the GA release of the grounding module.

**Comment by feng-lia** [comment]
> Could you please clarify the positioning of cap-llm-plugin versus the new [SAP Cloud SDK for AI](https://github.com/SAP/ai-sdk-js) ? The 2 libraries look to me a bit overlapping specially when document grounding will be part of orchestration.

cap-llm-plugin is relatively pertained to CAP development with the way you handle entities and columns, but you can always check both documents for more details to pick whatever fits your need.
