### ISSUE TITLE
Small issues in testing

### ISSUE THREAD

**Issue by DanSchlachter** [SAP-samples/cap-llm-plugin-samples#15]
Hi,

I configured the RAG Quickstart App with hybrid testing and ran into a few issues:

- In the inference API in the destination content and in the package json the `v2` is there in the URL, so after creating the full URL it is .../v2/v2/... and doesn't work
- It would be nice to already mention early in the tutorial, that two configurations / deployments are needed. I created the config for gpt-4 and had to come back for the text embeddings, which takes more time
- For me it wasn't clear, that the `apiVersion` in package.json and the `version` of the model are not similar and you have to go to the documentation of the respective models to find this parameter. Maybe this could be pointed out?
- Issue creation in readme https://github.com/SAP-samples/cap-llm-plugin-samples/pull/14/files

Thanks
Daniel

**Comment by feng-lia** [comment]
Hi Daniel,

Thank you for the feedback! Please check followings:
1. It is mentioned in the example readme at step 4 that the URL configured in Destination should be the host name of AI API  only without v2.
2. We will mention it in the readme.
3. ApiVersion and Model version are not defined in our cap-llm-plugin. We need to go to Model provider's doc for the right value. HOW-TO is mentioned in example readme at step 5 in the json config.
4. Link will be fixed.

Best~
