### ISSUE TITLE
Issue while generating Embeddings 

### ISSUE THREAD

**Issue by dileepsaccount** [SAP-samples/cap-llm-plugin-samples#16]
Hi Team,

I am getting the below error while generating the embeddings using the method getEmbeddingWithConfig.
      const embedding = await vectorPlugin.getEmbeddingWithConfig({
        destinationName: 'shopping-cart-v2-destination-service',
        modelName: 'text-embedding-ada-002',
        resourceGroup: 'default',
        deploymentUrl: 'https://api.ai.intprod-eu12.eu-central-1.aws.ml.hana.ondemand.com/v2/inference/deployments/dc4dbb973c9fa89c',
        apiVersion: '2024-06-01'
      }, chunk.pageContent);

**Error Details:**
Documents split into 6 chunks.
Generating the vector embeddings for the text chunks.
Processing chunk: Document {
  pageContent: 'type;name;descr\r\n' +
    '0001;Consumer Shopping Cart;Shopping cart for consumer business',
  metadata: {
    source: 'C:\\Dev\\ipe-ato-samples\\shopping-cart-v2\\db\\data\\com.sap.ipe.ato.chb.common-DocumentTypes.csv',
    loc: { lines: [Object] }
  },
  id: undefined
}
Config object: {
  destinationName: 'shopping-cart-v2-destination-service',
  modelName: 'text-embedding-ada-002',
  resourceGroup: 'default',
  deploymentUrl: 'https://api.ai.intprod-eu12.eu-central-1.aws.ml.hana.ondemand.com/v2/inference/deployments/dc4dbb973c9fa89c',
  apiVersion: '2024-06-01'
}
C:\Dev\ipe-ato-samples\shopping-cart-v2\node_modules\@sap\cds\lib\srv\factory.js:22
  async function _use (it) {
                      ^

RangeError: Maximum call stack size exceeded
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Upon debugging, i observed it call is getting into infinite loop from the factory.js. Could you please suggest and help resolving the issue

**Comment by feng-lia** [comment]
you should not use full link for deploymentUrl to define a config object. Like in the readme, the deploymentUrl should be 'v2/inference/deployments/dc4dbb973c9fa89c' , and recommended way is to follow Readme and define this in package.json. BTW, the host name for AI Hub is configured in destination.
