### ISSUE TITLE
Embedding generation failed (continued)

### ISSUE THREAD

**Issue by hm23** [SAP-samples/cap-llm-plugin-samples#17]
Hi @feng-lia ,

This is a follow-up of https://github.com/SAP-samples/cap-llm-plugin-samples/issues/11. The user reported in the last comment (and now also in a Service Now support ticket) that the issue persists. Could you please have a look once more?

From CAP side, I can't help here. It is correct that `cds.stream` won't work with cds 8, but in cds 7.6.3 (and cds 7.7.0) it still exists. If I read the stack trace correctly, the error is thrown in:
https://github.com/SAP-samples/cap-llm-plugin-samples/blob/2b9d4495916c6802244abde402168c8a14f42ad7/samples/hr-approval-rag-usecase/srv/embedding-storage.js#L68
... so it might be related to this `pdf-lib` module.

Thanks & best regards,
Heiko

**Comment by feng-lia** [comment]
Hi Heiko,
We tested the example locally and it runs without any issue. It does not seem to be related with the plugin lib nor the cds versions. We have sent you an email with detailed suggestions, we can continue from there.
Thank you~
