### ISSUE TITLE
function getRagResponse, enhancement to be able to add document filter logic

### ISSUE THREAD

**Issue by cocquerel** [SAP-samples/cap-llm-plugin-samples#5]
For the function getRagResponse, instead of providing a table name that contains vector embeddings, I would like to be able to provide a view name together with parameter value. The reason is because, in my use case, I would like to be able to implement a filter logic based on document metadata to restrict the documents I want to consider when searching for similar vector.

**Comment by shumagundam** [comment]
Is there any update on this question? I'm also having the same issue.

**Comment by feng-lia** [comment]
currently you have to filter the similarity search results in your own code. We will look into this capability once CQL supports related hana vector engine features.
