### ISSUE TITLE
General Information about the current status of the repository

### ISSUE THREAD

**Issue by t0biW** [SAP-samples/cap-llm-plugin-samples#6]
Hi,
I stumbled upon this repository, and I would like to try it out and maybe use parts of it in future projects. Now I would like to know if updates can be expected in this repository or if current versions of this approach are stored elsewhere. 

Thanks kindly.

**Comment by feng-lia** [comment]
Hi, this repo would contain examples and docs regarding the plugin of different versions. For latest version and its source code, you can check what is released to NPM.
